baseURL = 'https://behura.com'
languageCode = 'en-us'
title = 'Ankita Behura'
theme= 'mainroad'

[menu]
    [[menu.main]]
    name = "About"
    url= "/about/"
    weight= 1

    [[menu.main]]
    name = "Devops"
    url= "/devops/"
    weight= 1

    [[menu.main]]
    name = "ML/DL"
    url= "/ml-dl/"
    weight= 1

    [[menu.main]]
    name = "Random"
    url= "/random/"
    